resources:
  - url: http://127.0.0.1:5000/decluttering-card.js
    type: module
  - url: https://cdn.jsdelivr.net/gh/thomasloven/lovelace-card-mod@master/card-mod.js
    type: module

decluttering_templates:
  my_first_template: # This is the name of a template
    default:
      - icon: fire
    card:
      type: button
      name: '[[name]]'
      icon: 'mdi:[[icon]]'
  large_divider:
    default:
      - opacity: 0.25
    card:
      type: divider
      style:
        background-color: var(--secondary-text-color)
        height: 1px
        margin: 15px auto
        opacity: '[[opacity]]'
  demo_icon:
    element:
      type: icon
      icon: mdi:alert-circle
      title: Problem detected!
      entity: '[[entity]]'
      tap_action:
        action: more-info
      style:
        right: 50%
        top: 50%
        color: var(--google-red-500)
        filter: drop-shadow(black 0 0 1px)
  test_hidden:
    card:
      type: conditional
      conditions:
        - entity: light.bed_light
          state: 'on'
      card:
        type: entities
        entities:
          - sun.sun

views:
  - cards:
      - type: custom:decluttering-card
        template: my_first_template
        variables:
          - name: This is a test
      - type: entities
        entities:
          - light.bed_light
          - type: custom:decluttering-card
            template: large_divider
          - sun.sun
      - type: picture-elements
        image: https://www.w3schools.com/w3css/img_lights.jpg
        elements:
          - type: custom:decluttering-card
            template: demo_icon
            variables:
              - entity: sun.sun
      - type: horizontal-stack
        cards:
          - type: custom:decluttering-card
            template: my_first_template
            variables:
              - name: Full width when light Off
          - type: custom:decluttering-card
            template: test_hidden
